---
name: ISort

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  isort-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1.0.0
#        with:
#          requirements-files: "requirements.txt requirements-test.txt"
